# ──────────────────────────────────────────────
# Cloudflare Pages — Common Bond Corporate Documentation
# Site: https://docs.commonbond.au/corporate/
# ──────────────────────────────────────────────

name = "doco-common-bond"
compatibility_date = "2025-01-01"
pages_build_output_dir = "build"
